# Generated by Django 5.1.4 on 2026-08-17 09:23

import apps.vendors.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Public/brand contact email, may differ from login email.', max_length=254)),
                ('brand_name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.vendors.models.vendor_avatar_path)),
                ('is_activated', models.BooleanField(default=False, help_text='Approved by admin to sell.')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('is_diamond', models.BooleanField(default=False, help_text='Top-tier vendor badge.')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Platform commission percentage taken from each sale.', max_digits=5)),
                ('total_sales_ever', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
